version: 1.2
workflows:
  - subclass: <WDL>
    primaryDescriptorPath: <String>  # absolute path
    testParameterFiles: <String Array>  # absolute path
    readMePath: <String> # absolute path
    authors:
      - name: <Junhui Li>
        email: <ljh.biostat@gmail.com>
